{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ template "atlantis.fullname" . }}
  labels:
{{- include "atlantis.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}  
spec:
  selector:
    matchLabels:
{{- include "atlantis.labels" . | nindent 6 }}
  endpoints:
  - port: atlantis
    interval: {{ .Values.podMonitor.interval }}
{{- end -}}
